## Carregamendo do gabarito  
  

Com base no conteúdo rotulado nas duas bases BOS.xlsx e DECC.xlsx aqui é realizado o carregamento do gabarito.

In [1]:
import os
import re
import unicodedata
import pandas as pd
from unidecode import unidecode

In [2]:
import nltk
nltk.download('stopwords')

from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\joaol\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [3]:
PATH_BASE_BOS = os.getenv('PATH_BASE_BOS')
PATH_BASE_DECCC = os.getenv('PATH_BASE_DECCC')
PATH_GABARITO = os.getenv('PATH_GABARITO')

### Carregando a Base

In [4]:
df_origin = pd.read_excel(PATH_BASE_BOS, usecols=['n_bop', 'relato', 'NOMES']).dropna(subset=['NOMES']).reset_index()
df_new = pd.read_excel(PATH_BASE_DECCC, usecols=['n_bop', 'relato', 'nomes']).dropna(subset=['nomes']).reset_index()

df = pd.DataFrame({'n_bop':pd.concat([df_origin['n_bop'], df_new['n_bop']], ignore_index=True),
                    'relato':pd.concat([df_origin['relato'], df_new['relato']], ignore_index=True),
                    'nomes': pd.concat([df_origin['NOMES'], df_new['nomes']], ignore_index=True)})
df

,n_bop,relato,nomes
0,00615/2021.100191-1,"A DECLARANTE ACIMA QUALIFICADA, INFORMA QUE E...","MANDA, FARIAS, SERIA, POLO, WILLIAN"
1,00616/2021.100053-9,A RELATORA ACIMA QUALIFICADA COMPARECE NESTA ...,"EDUARDO, HELIO, PEREIRA, DIAS, MALA, ELIAS, IR..."
2,00616/2021.100190-3,A RELATORA ACIMA QUALIFICADA COMPARECE NESTA ...,"EDUARDO, SILVA, PEREIRA, JOSE, PAULO, MARTINIA..."
3,00616/2021.100222-0,A RELATORA ACIMA QUALIFICADA COMPARECE NESTA ...,ERALDO
4,00616/2021.100016-0,O RELATOR ACIMA QUALIFICADO COMPARECE NESTA D...,"FERNANDA, VIVIANE, IRIA, ALEM, REGINA"
...,...,...,...
766,00487/2020.100303-9,O RELATOR COMPARECE NESTA DIVISAO DE POLICIA ...,"ELITO, FONSECA, CORREA"
767,00615/2020.100363-4,A VITIMA RELATA QUE NO DIA E HORA SUPRACITADO...,"WELLINGTON, ALAN, MACEDO, CHAVES, LEONARDO, AR..."
768,00615/2020.100847-3,A CIDADA ACIMA QUALIFICADA COMPARECEU NESTA D...,"MARCIA, PRISCILA, MARIA, EDILVA, ALVES, SILVA"
769,00615/2020.100746-2,A RELATORA COMPARECE NESTA DIVISAO DE POLICIA...,"JACKELINE, GELENE,"
770,00615/2020.100567-5,A VITIMA COMPARECEU NESTA DIVISAO ESPECIALIZA...,"IVO, VANCHO, PANOVICH, VIVIANE, GOMES"

In [3]:
df = pd.read_csv(r'C:\Users\joaol\OneDrive\Desktop\MestradoBaseMédica\ProjetoDoutorado\BASES\base_dados_medica_com_id.csv', usecols=['relato', 'nomes']).dropna(subset=['nomes']).reset_index(drop=True)

### Pré-processamento nos relatos

In [4]:
def preprocess(relato):
    def remove_stop_words(relato):
        # Remove stop words em português
        sw = stopwords.words('portuguese')
        sw = [unidecode(word).upper() for word in sw]
        return ' '.join([token for token in re.split("[, ]", relato) if len(token) > 2 and token not in sw])
    
    def clean_relato(relato):
        # Remoção de números e pontuação    
        relato = re.sub(r'\@(\w*\d?)', " ", relato)
        relato = re.sub(r'([A-z1-9]*_+[A-z1-9]*)|(_+[A-z1-9]*)|([A-z1-9]*_+)', " ", relato)
        relato = re.sub(r"((?:HTTPS?|WWW)(?:\:\/\/?)?[*a-zA-Z0-9\.\/\?\:@\-_=#]+[\.][a-zA-Z]{2,6}[a-zA-Z0-9\.\&\/\?\:@\-_=#]*)", " ", relato)
        relato = re.sub(r'(<[^<>]*>)|(&NBSP;)|(&nbsp;)', " ", relato)
        relato = re.sub(r"[^\w\s]", " ", relato)
        relato = re.sub(r"[\d]", " ", relato)
        relato = remove_stop_words(relato)
        return relato
    
    relato = clean_relato(relato)
    return relato

def normalize_text(text):
    if pd.isna(text):
        return text
    text = unicodedata.normalize('NFKD', text)
    text = ''.join(c for c in text if not unicodedata.combining(c))
    return text.upper()

In [5]:
df['relato'] = df['relato'].apply(normalize_text)
df['relato_tratado'] = df['relato'].apply(preprocess)

### Extração dos nomes da coluna de rótulos

In [6]:
coluna_nomes_base = [re.split(r', | |,', df['nomes'][i]) for i in range(0,len(df))]

In [7]:
def load_names_base(coluna_nomes_base):
    lista_nomes = []
    for value in coluna_nomes_base:
        for non in value:
            lista_nomes.append(non)
    print("Tamanho original antes da remoção de duplicados: ", len(lista_nomes))
    return set(lista_nomes)

In [8]:
nomes = load_names_base(coluna_nomes_base)

Tamanho original antes da remoção de duplicados:  13400

In [9]:
print("Tamanho após a remoção dos duplicados: ", len(nomes))

Tamanho após a remoção dos duplicados:  638

### Obtenção da coluna de relatos e transformar em tokens

In [10]:
coluna_relato_base = [df['relato_tratado'][i].split(' ') for i in range(0,len(df))]

In [11]:
def load_words_base(coluna_relato_base):
    lista_relatos = []
    for value in coluna_relato_base:
        for word in value:
            lista_relatos.append(word)
    print("Tamanho original antes da remoção de duplicados: ", len(lista_relatos))
    return set(lista_relatos)

In [12]:
palavras = load_words_base(coluna_relato_base)

Tamanho original antes da remoção de duplicados:  231798

In [13]:
print("Tamanho após a remoção dos duplicados: ", len(palavras))

Tamanho após a remoção dos duplicados:  11528

### Veficação da existencia de dados repetidos

In [14]:
df_nomes = pd.DataFrame({'nomes':list(nomes)})
df_palavras = pd.DataFrame({'palavras':list(palavras)})

### Removendo valores vazios nas celulas

In [15]:
df_nomes = df_nomes.replace({'':None})
df_nomes = df_nomes.dropna()

In [16]:
df_palavras = df_palavras.replace({'':None})
df_palavras = df_palavras.dropna()

In [17]:
df_palavras

           palavras
0      VASOPRESSORA
1           HIDRICA
2       OSTEOPOROSE
3           FAMILIA
4             NOTED
...             ...
11523        ICARAI
11524  PROCEDIMENTO
11525         AMARO
11526     PONTUACAO
11527  DESCONFORTOS

[11528 rows x 1 columns]

In [18]:
df_palavras[df_palavras['palavras'].isin(df_nomes['nomes'].to_list())]

       palavras
5      MAURICIO
34      PORTELA
87       BORGES
101       JULIO
104    SIQUEIRA
...         ...
11472   NOBREGA
11475    SANTOS
11483   LUCIANO
11492   SALGADO
11519  FERNANDO

[535 rows x 1 columns]

In [19]:
df_palavras = df_palavras[~df_palavras['palavras'].isin(df_nomes['nomes'].to_list())].reset_index(drop=True)

In [20]:
df_palavras[df_palavras['palavras'].isin(df_nomes['nomes'].to_list())]

Empty DataFrame
Columns: [palavras]
Index: []

In [21]:
df_palavras

           palavras
0      VASOPRESSORA
1           HIDRICA
2       OSTEOPOROSE
3           FAMILIA
4             NOTED
...             ...
10988        ICARAI
10989  PROCEDIMENTO
10990         AMARO
10991     PONTUACAO
10992  DESCONFORTOS

[10993 rows x 1 columns]

In [22]:
df_nomes['y'] = 1
df_palavras['y'] = 0

In [23]:
tokens = df_nomes['nomes'].to_list() + df_palavras['palavras'].to_list()

In [24]:
tokens

['MARIETA',
 'LUZ',
 'ELIANE',
 'GUSMÃO',
 'MAURICIO',
 'CARLOS',
 'SÔNIA',
 'ABREU',
 'DIEGO',
 'MARTHA',
 'PIETRA',
 'BRAGA',
 'EVANDRO',
 'ULISSES',
 'CLÁUDIA',
 'ROMILDO',
 'LUAN',
 'JUAREZ',
 'MANUELA',
 'TEREZA',
 'PORTELA',
 'FERRAZ',
 'JOCIELE',
 'LÚCIA',
 'VINICIUS',
 'VINÍCIUS',
 'ASSIS',
 'PEREIRA',
 'HEITOR',
 'ESTEVÃO',
 'CECÍLIA',
 'MADUREIRA',
 'MAISONNAVE',
 'MARCUS',
 'JOÃO',
 'FUJITA',
 'LEONARDO',
 'CAMILA',
 'E',
 'RIOLO',
 'CARINA',
 'YARA',
 'MARISTELA',
 'MASCARENHAS',
 'MOLINAS',
 'MENEZES',
 'ALFREDO',
 'JONAS',
 'PÊGO',
 'LOUREIRO',
 'FRAGA',
 'VERDE',
 'BICALHO',
 'EDGAR',
 'ANSELMO',
 'SOUZA',
 'CRISTINA',
 'GUERRA',
 'LEANDRO',
 'FREITAS',
 'SIMÕES',
 'ROGÉRIO',
 'THAIS',
 'MARTINS',
 'RITA',
 'F',
 'MIRANDA',
 'JÉSSICA',
 'MOURA',
 'HUGO',
 'ESPINOSA',
 'MARQUEZ',
 'BIA',
 'ORLANDO',
 'BORGES',
 'LÍDIA',
 'MARCOS',
 'NOVAES',
 'SENNA',
 'TEREZINHA',
 'CECCON',
 'ELENA',
 'MATOS',
 'MUNIZ',
 'PRADO',
 'MURILO',
 'JULIO',
 'CASSIA',
 'C.',
 'SIQUEIRA',
 'AGUIAR',
 'CESAR',
 'APARECIDA',
 'OTÁVIO',
 'FELIPE',
 'ALBUQUERQUE',
 'MAURÍCIO',
 'ERIKA',
 'BÔAS',
 'ROMILDA',
 'RAIMUNDO',
 'PORTELLA',
 'EDNALDO',
 'KUROSKI',
 'PERINNI',
 '+',
 'PACHECO',
 'CARMEN',
 'SARA',
 'MATIAS',
 'MARINHO',
 'PALOMA',
 'PONTES',
 'JULIANA',
 'ROBERTO',
 'ADRIELLE',
 'LOPES',
 'GARCIA',
 'ADRIANA',
 'SOUTO',
 'DO',
 'SABATINE',
 'MONTEIRO',
 'DANTAS',
 'PIRES',
 'BASTOS',
 'VARGAS',
 'SILVEIRA',
 'LUÍSA',
 'ALVES',
 "D'ARC",
 'LORENZZONI',
 'AINHOA',
 'C',
 'CAROL',
 'CERATI',
 'ANDERSON',
 'GUSTAVO',
 'LUCIA',
 'LOBO',
 'JOAQUIM',
 'FERNÃO',
 'JULIANO',
 'HARADA',
 'ANDRE',
 'JUNQUEIRA',
 'GUIMARÃES',
 'TATIANA',
 'NASCIMENTO',
 'DR',
 'QUINTAS',
 'ÁVILA',
 'PORTO',
 'BOAS',
 'BEATRIZ',
 'DUARTE',
 'DAS',
 'RAMOS',
 'RIOS',
 'PENA',
 'LÍGIA',
 'CLARISSA',
 'SONIA',
 'DR.',
 'JOHN',
 'JÚLIO',
 'R2',
 'SILVA',
 'CLAUDIA',
 'MIRELA',
 'ANNA',
 'RENATO',
 'MARIANA',
 'LUNA',
 'MARCELO',
 'ESTRELA',
 'VICTOR',
 'IVERKE',
 'MATHEUS',
 'SÉRGIO',
 'P',
 'REZENDE',
 'PATRICIA',
 'SÍLVIA',
 'VIANA',
 'SUSANA',
 'ALVAREZ',
 'CAVALCANTE',
 'EDUARDA',
 'MARIANE',
 'ANTONIO',
 'JOSEFINA',
 'MAIA',
 'S.',
 'EVALDO',
 'ESTHER',
 'ALMEIDA',
 'MARGARETE',
 'ANTONELLI',
 'JUAN',
 'ABEL',
 'MÃE',
 'LIA',
 'LAURA',
 'EDSON',
 'HENRIQUES',
 'CARMEM',
 'CÉLIA',
 'ALEX',
 'ANDRÉA',
 'MIRELLA',
 'LOURENÇO',
 'SAMPAIO',
 'RICARDO',
 'LEITE',
 'ARAÚJO',
 'FILHO',
 'RENATA',
 'AURÉLIO',
 'JACINTO',
 'D’ARC',
 'NOGUEIRA',
 'NETO',
 'MIGUEL',
 'T.',
 'FARIAS',
 'TULIO',
 'ARANTES',
 'PAULO',
 'FRANTZ',
 'CORRÊA',
 'SCHMIDT',
 'NICOLAS',
 'BEZERRA',
 'RAIMUNDA',
 'CELINA',
 'RAFAEL',
 'JESSICA',
 'PINHEIRO',
 'XAVIER',
 'TELLES',
 'RODRIGUES',
 'VIVIAN',
 'MCCOY',
 'CARMONA',
 'FERNANDEZ',
 'ANTÔNIO',
 'JR.',
 'ALESSANDRO',
 'TÚLIO',
 'ALVARENGA',
 'DANIELA',
 'BARRETO',
 'GUILHERME',
 'PEDRO',
 'SANTANA',
 'NISHIMURA',
 'SPINELLI',
 'GAMA',
 'NUNES',
 'MARTINEZ',
 'GOUVEIA',
 'SOPHIA',
 'FRANCISCO',
 'GONÇALVES',
 'ENFERMEIRO',
 'AMADO',
 'ANTÓNIO',
 'CLARA',
 'JORGE',
 'ENZO',
 'TANAKA',
 'MÁRCIA',
 'ADRIANO',
 'INÊS',
 'MARLENE',
 'LETÍCIA',
 'CAROLINE',
 'KARINA',
 'CERQUEIRA',
 'LEME',
 'SERGIO',
 'M.',
 'BATISTA',
 'MÁRIO',
 'BICUDO',
 'PINTO',
 'MARTA',
 'GOULART',
 'LUIZA',
 'PAULA',
 'LUISA',
 'MATEUS',
 'ELAINE',
 'ELIS',
 'RIBEIRO',
 'REINALDO',
 'VITOR',
 'MENDES',
 'REIS',
 'ARTUR',
 'ENRIQUE',
 'JOANA',
 'MEDEIROS',
 'CAMPOS',
 'MARQUES',
 'LUIS',
 'BARRIGA',
 'FRANCA',
 'COUTO',
 'RODRIGO',
 'IBRAHIM',
 'ALICE',
 'SUELI',
 'JAVIER',
 'LINS',
 'ELIZA',
 'DRA',
 'LINARES',
 'ALCANTARA',
 'CABRAL',
 'MONTES',
 'FABIANO',
 'GABRIELA',
 'MARISA',
 'FRANCO',
 'VAZ',
 'ANTONIETA',
 'TRANCOSO',
 'R.',
 'GIOVANA',
 'DE',
 'ALENCAR',
 'MENEGHINI',
 'MACEDO',
 'LARA',
 'SÍLVIO',
 'QUEIROS',
 'LISBOA',
 'SÁ',
 'CAIO',
 'OSVALDO',
 'MENESES',
 'CAMARGO',
 'GABRIELLE',
 'MARCELA',
 'MARÍLIA',
 'ALESSANDRA',
 'QUINTELLA',
 'FIGUEIRA',
 'DINIZ',
 'CLAUDEMIR',
 'MARCO',
 'Q',
 'PAZ',
 'COSTA',
 'SOFIA',
 'LOUZADA',
 'SOLANGE',
 'MENDONÇA',
 'LEONARD',
 'LARISSA',
 'NAKAMURA',
 'FARIA',
 'MOTTA',
 'GIOVANNI',
 'P.',
 'BANDEIRAS',
 'GABRIEL',
 'VILLAR',
 'PABLO',
 'GERTRUDES',
 'PINHO',
 'TEIXEIRA',
 'ANA',
 'REBECA',
 'ANACLETO',
 'LIRA',
 'ELIANA',
 'CASTILHO',
 'VIEIRA',
 'LEMOS',
 'CARVALHO',
 'SAMANTHA',
 'ALMEIRA',
 'CORREA',
 'SAMUEL',
 'SERRANO',
 'CAROLINA',
 'LUCIANA',
 'EDUARDO',
 'ALVARO',
 'VIEGAS',
 'THIAGO',
 'TATIANE',
 'FIGUEIREDO',
 'JÚNIOR',
 'EMANUEL',
 'PORTILHO',
 'BERALDO',
 'JOSÉ',
 'MARIO',
 'MALAVAZI',
 'MELLO',
 'FONTES',
 'ROSA',
 'MARÍA',
 'DOMINGOS',
 'DRUMMOND',
 'ROSATI',
 'LAGO',
 'MONTENEGRO',
 'CLARICE',
 'MEIRELES',
 'BIANCA',
 'JULIA',
 'CARLA',
 'OCUPA',
 'FAGUNDES',
 'ALENCASTRO',
 'CARNEIRO',
 'WRIGHT',
 'SANDRA',
 'MARINA',
 'TINOCO',
 'BARROS',
 'DORES',
 'FONTANA',
 'CORTEZ',
 'LUCAS',
 'SANCHES',
 'GOMEZ',
 'EGUÍA',
 'VAZQUEZ',
 'ROBERTA',
 'CRUZ',
 'DENISE',
 'GONZAGA',
 'GOMES',
 'ALBERTO',
 'FONTOURA',
 'JÚLIA',
 'PEIXOTO',
 'PIZA',
 'CASTRO',
 'GRAÇAS',
 'BARBOSA',
 'SILVIO',
 'R3',
 'TIAGO',
 'VILLAS',
 'JOSE',
 'ROSANA',
 'ESTEVES',
 'ANTÔNIA',
 'TAVARES',
 'TORRES',
 'VELASCO',
 'CÉSAR',
 'ARTHUR',
 'DÉBORA',
 'FONSECA',
 'MANUEL',
 'SUGAHARA',
 'STEPHANIE',
 'FASSINA',
 'SANTIAGO',
 'GIMENEZ',
 'TERESA',
 'LUÍS',
 'ELISA',
 'MAGNO',
 'SILVANA',
 'AYRES',
 'CÍNTIA',
 'RANGEL',
 'GUEDES',
 'AUGUSTO',
 'CARMO',
 'VIVIANE',
 'AURELIO',
 'NEVES',
 'ALEGRE',
 'VANESSA',
 'AMANDA',
 'CLÁUDIO',
 'FURTADO',
 'MELO',
 'SILVIA',
 'LACERDA',
 'MACHADO',
 'MELISSA',
 'NEUROLOGISTA',
 'ÉRICA',
 'MARTIN',
 'CORREIA',
 'TOLEDO',
 'ELOISA',
 'AZEVEDO',
 'ASSUNÇÃO',
 'ZARATE',
 'ARNALDO',
 'LORENA',
 'CORDEIRO',
 'MATTOS',
 'LIDIANE',
 'FERREIRA',
 'LAZZAROTTO',
 'COELHO',
 'VILAS',
 'ISABELA',
 'NOBRE',
 'QUEIRÓS',
 'MÁRCIO',
 'ROCHA',
 'HELENA',
 'ORSIA',
 'MOTA',
 'MAURO',
 'LETICIA',
 'SIMONE',
 'ISABELLA',
 'OLIVEIRA',
 'TADEU',
 'FABIO',
 'FERNANDA',
 'ALCÂNTARA',
 'MEIRELLES',
 'TERESINHA',
 'SANTINI',
 'CLAUDIO',
 'APARECIDO',
 'PRISCILA',
 'CUNHA',
 'MARCONDES',
 'ALVARES',
 'VALTER',
 'ANTUNES',
 'MARCIA',
 'F.',
 'RAQUEL',
 'AMARAL',
 'AFONSO',
 'LUCCA',
 'LUIZ',
 'DANIEL',
 'HENRIQUE',
 'VENTURA',
 'YOOTID',
 'FUENTES',
 'ISABEL',
 'DIAZ',
 'ELISABETH',
 'TORQUATO',
 'LUÍZA',
 'JUNIOR',
 'MARIA',
 'ISADORA',
 'SANTARELLI',
 'MAGALHÃES',
 'ESTEVAM',
 'SOUSA',
 'LÍVIA',
 'LUANA',
 'ALINE',
 'MOREIRA',
 'ÁLVARO',
 'FERNANDES',
 'SOARES',
 'PATRÍCIA',
 'IRACEMA',
 'RABELO',
 'VASCONCELOS',
 'FUKUI',
 'ORTIZ',
 'RAFAELA',
 'R1',
 'MÔNICA',
 'MORAES',
 'CASTELO',
 'JAIRO',
 'RODRIGUEZ',
 'FRANÇA',
 'ALEXANDRE',
 'ÂNGELO',
 'BITTENCOURT',
 'ANDRADE',
 'VERA',
 'G.',
 'VERÔNICA',
 'DIAS',
 'MARINHEIRO',
 'GLAUCIA',
 'NOBREGA',
 'SARTORI',
 'BERNARDES',
 'LÚCIO',
 'CM',
 'MARGARIDA',
 'HELOÍSA',
 'REGINA',
 'SANTOS',
 'KARLA',
 'FÁBIO',
 'MUSSI',
 'JOAQUINA',
 'ARRUDA',
 'VALENTE',
 'LUCIANO',
 'SOBRAL',
 'VILLA',
 'MORAIS',
 'ALONSO',
 'ANJOS',
 'FABIANA',
 'L.',
 'DA',
 'CARDOSO',
 'SALGADO',
 'ANDRÉ',
 'BRUNO',
 'JOSIAS',
 'DOS',
 'RUBENS',
 'DOLORES',
 'QUEIROZ',
 'RAFAELLA',
 'LIAM',
 'BRANCO',
 'BRUNA',
 'FERNANDO',
 'FLÁVIA',
 'ANTONIA',
 'VEIGA',
 'FREIRE',
 'LIMA',
 'GIOVANNA',
 'SOBRINHO',
 'VASOPRESSORA',
 'HIDRICA',
 'OSTEOPOROSE',
 'FAMILIA',
 'NOTED',
 'URINALISE',
 'APLICAR',
 'VESICULARES',
 'PERFUNDIDOS',
 'INCIPIENTE',
 'ESTALO',
 'ASSEADA',
 'ACONSELHADA',
 'VIAS',
 'ANOSMIA',
 'FOSSA',
 'INCENTIVADO',
 'DESINFORMACAO',
 'CATOLICA',
 'MRC',
 'ICC',
 'PREGA',
 'AJUSTE',
 'REPETITIVO',
 'THIGH',
 'VALE',
 'NIHSS',
 'PROGRESSO',
 'EPISODIO',
 'PEDIDO',
 'LESAO',
 'PRECOCES',
 'CISTINA',
 'DISARTICULACAO',
 'CIDADE',
 'NORMALIZADA',
 'PATOLOGICAS',
 'CORONARIANAS',
 'BEATRIZDUARTE',
 'DISCECTOMIA',
 'CARDIOGENICO',
 'PRESENCIAL',
 'PAM',
 'MEIO',
 'ESPINHAL',
 'DETALHAMENTO',
 'NUTRICIONISTA',
 'MOMENTO',
 'EXTRACORPOREA',
 'AMANHECER',
 'PERDEU',
 'CARBONATO',
 'CACHOEIRA',
 'DIRETRIZ',
 'ABD',
 'DESCREVENDO',
 'EDUCACIONAL',
 'EXTRUSA',
 'TRIARTERIAL',
 'BRUDZINSKI',
 'BENEFICIO',
 'PREVISAO',
 'OBSERVA',
 'WORK',
 'CRANIANO',
 'ULTIMOS',
 'SEVEROS',
 'ANTICOAGULADA',
 'PIORARAM',
 'VEIO',
 'FOCAL',
 'DAQUI',
 'NESTE',
 'LER',
 'SEGUROS',
 'FUNCIONALIDADE',
 'PERCEPTIVOS',
 'AVD',
 'HIPODENSAS',
 'FRUTAS',
 'ADMISSIONAL',
 'APRECIA',
 'MOTION',
 'CARRO',
 'BENZODIAZEPINICO',
 'MACROSCOPICA',
 'GIARDIASE',
 'AMIGOS',
 'FLACIDEZ',
 'MAXIMAS',
 'ACATADO',
 'CORPORAL',
 'COGNITIVOS',
 'SEGURA',
 'ABANDONO',
 'OBTEVE',
 'NIQUEL',
 'ENGOLIR',
 'INFORMADA',
 'FREELANCER',
 'LINGUA',
 'VAZAMENTO',
 'TORNOZELO',
 'DISPERSA',
 'UNIVERSAIS',
 'PROGRAMA',
 'DEGLUTICAO',
 'SEGUINDO',
 'LINFADENOPATIA',
 'LEVA',
 'DOSES',
 'GENETICAS',
 'PATENTES',
 'LERGIAS',
 'DURAL',
 'PERTO',
 'PRETO',
 'ESTRANHAS',
 'BUDENOFINA',
 'OPTIMIZACAO',
 'IMPROVEMENT',
 'HIPOTENSIVA',
 'CONDROMALACIA',
 'EXTERNO',
 'FLUXO',
 'PSIQUIATRICO',
 'OTIMIZACAO',
 'SENTIDO',
 'ATIPICA',
 'HIPOLIPIDICA',
 'VIVENCIA',
 'NENHUM',
 'CALCULADO',
 'CONTINUAMOS',
 'ADERENCIAL',
 'CONTATEI',
 'SENSORY',
 'NORMOGLICEMICO',
 'SGLT',
 'MULTIFRAGMENTARIA',
 'INOTROPICOS',
 'ANGINOSA',
 'PNEUMOCOCO',
 'PSICOPEDAGOGICA',
 'GERALMENTE',
 'FERIDAS',
 'ESOFAGO',
 'ELETRICAS',
 'LOEFFLER',
 'LENTO',
 'UPTAKE',
 'APOIAR',
 'MBARROS',
 'RETARDED',
 'HYPERTENSIVE',
 'ESTOMA',
 'SULFASSALAZINA',
 'LAPSOS',
 'ENFERMAGEM',
 'VONTADE',
 'TEMPORO',
 'OFTALMOLOGISTA',
 'GINECOLOGIA',
 'RIVAROXABANA',
 'ESTAVEIS',
 'APROXIMADAMENTE',
 'CALORICO',
 'GABAPENTINA',
 'RESSINCRONIZADORA',
 'CIRURGIAO',
 'TRAUMATOLOGIA',
 'PRESERVADAS',
 'SPEECH',
 'COMENTARIOS',
 'DIVERTICULOS',
 'SETES',
 'PRESCRICOES',
 'PRAZOSINA',
 'SISTOLICOS',
 'BACTERIANA',
 'INUTILIDADE',
 'AGHUSE',
 'LENTA',
 'FLAMBOYANT',
 'PERSISTENT',
 'AVERIGUAR',
 'QUALIFICADO',
 'ESTRABISMO',
 'LUMBARPUNCTURA',
 'ENTANTO',
 'CHOLESTEROL',
 'FLASHBACKS',
 'MONITORIZADOS',
 'SENSORIAL',
 'CAMPINAS',
 'PESSOAL',
 'LABORATORIO',
 'MENINGEOS',
 'TUMORAIS',
 'CONJUGAL',
 'PLANTONISTA',
 'ENTEROCOLITE',
 'CIRGERAL',
 'FORNECEU',
 'INTERESSES',
 'DIRETA',
 'ULG',
 'AUTOINJECAO',
 'AGUARDANDO',
 'OPONENCIA',
 'TROMBOLITICA',
 'EFETIVIDADE',
 'AVANCADO',
 'CORREDOR',
 'SEDIMENTACAO',
 'IGE',
 'EVIDENCIOU',
 'HBA',
 'COMPENSADO',
 'COLHIDAS',
 'ENCAMINHAMENTO',
 'OCLUSIVO',
 'OPOSITIVO',
 'AUTOLOGO',
 'EXPANSORES',
 'CONTROLAVEL',
 'ECOGRAFICA',
 'FETAIS',
 'NOCICEPTIVOS',
 'LIMOEIRO',
 'LOGICO',
 'PROPRIO',
 'ASSOCIOU',
 'COMPLICACAO',
 'SITUADA',
 'TERATOMA',
 'COMPATIVEIS',
 'ATENCIOSAMENTE',
 'DERIVACOES',
 'NEUTROPENICA',
 'ELEVAR',
 'ANTIPLAQUETARIA',
 'PRECORDIO',
 'FALECIDO',
 'UPS',
 'EXERCICIO',
 'ANSIOSOS',
 'FICTICIAS',
 'DESESPERANCA',
 'SUBCUTANEO',
 'QUADRA',
 'NORTRIPTILINA',
 'RECUSA',
 'DENGUE',
 'COMPARTIMENTO',
 'AGORA',
 'FARMACOS',
 'ATENCAO',
 'LINFONODOS',
 'DURANTE',
 'LINFEMA',
 'CARPO',
 'NEGLIGENCIADO',
 'INSTALADO',
 'MUSCULORRELAXANTE',
 'INTERCOSTAL',
 'VASCULARES',
 'ARAUJO',
 'GASTRICA',
 'CREPITANTES',
 'MACOS',
 'REGURGITACOES',
 'ESQUELETO',
 'ANAOLIVEIRA',
 'SURGIR',
 'LIPIDEOS',
 'OXCARBAZEPINA',
 'INDICE',
 'RESERVADA',
 'DETECTO',
 'JUGULAR',
 'QUEIMACAO',
 'PORT',
 'PIRIMETAMINA',
 'APRESENTAR',
 'ESTATUS',
 'TAQUICARDICOS',
 'GANGLIOS',
 'ABSOLUTO',
 'TRAUMATICA',
 'EZETIMIBA',
 'AGREGADOS',
 'CIRURGICO',
 'DESPERTARES',
 'NUCAL',
 'ACOMPANHO',
 'PAPILIFERO',
 'SENSORIAIS',
 'DETALHO',
 'PROSTATA',
 'ROSSI',
 'RELACIONADO',
 'ONDANSETRONA',
 'VAGAS',
 'BIPERIDENO',
 'RECEBIDO',
 'SOLICITOU',
 'HORARIO',
 'EVIDENCIANDO',
 'LCA',
 'ELEMENTARES',
 'UNREMARKABLE',
 'LIBERACAO',
 'MELHOR',
 'HIPERTONIA',
 'REGISTRADO',
 'ETILISTA',
 'PROCESSAMENTO',
 'MARCELOSANTOS',
 'CODEINA',
 'POSSIVEL',
 'VAGINAL',
 'VIVA',
 'PICADAS',
 'LINFONODO',
 'ALERTAR',
 'HIPERTROFICA',
 'PLASMATICAS',
 'BACIA',
 'ABDOMINAL',
 'INSPIRACAO',
 'MIELO',
 'ANURIA',
 'SUSPENSOS',
 'ESCADAS',
 'PASSAGEM',
 'PLAN',
 'FMUSP',
 'FISIOTERAPIA',
 'SESSAO',
 'OBTER',
 'ESCOLAR',
 'EMERGENCIALMENTE',
 'PARIETAL',
 'RONCOS',
 'UTILIZA',
 'TRABALHAVA',
 'SEMESTRALMENTE',
 'JOELHOS',
 'LIDAR',
 'AVANCO',
 'IMUNIZACAO',
 'FELT',
 'DECISAO',
 'ANTIAGREGANTES',
 'VOLTADA',
 'SATURACOES',
 'FUNDOS',
 'TEMPO',
 'LUMINOSOS',
 'DIARIAS',
 'DEUS',
 ...]

In [25]:
rotulos = df_nomes['y'].to_list() + df_palavras['y'].to_list()

In [26]:
gabarito = pd.DataFrame({'palavra':tokens, 'y':rotulos}).dropna()

In [27]:
gabarito

            palavra  y
0           MARIETA  1
1               LUZ  1
2            ELIANE  1
3            GUSMÃO  1
4          MAURICIO  1
...             ... ..
11626        ICARAI  0
11627  PROCEDIMENTO  0
11628         AMARO  0
11629     PONTUACAO  0
11630  DESCONFORTOS  0

[11631 rows x 2 columns]

In [28]:
gabarito = gabarito.drop_duplicates(subset=['palavra'])
gabarito

            palavra  y
0           MARIETA  1
1               LUZ  1
2            ELIANE  1
3            GUSMÃO  1
4          MAURICIO  1
...             ... ..
11626        ICARAI  0
11627  PROCEDIMENTO  0
11628         AMARO  0
11629     PONTUACAO  0
11630  DESCONFORTOS  0

[11631 rows x 2 columns]

### Correção gab - removendo stopwords que sobraram

Alguns nomes possuem tokens "stopwords" como "AQUELES" ou "AQUELE" essa etapa é pra realizar a remoçao destes. Devido problemas que ocorreram no momento da avalização, os tokenizadores do Bert e Spacy removeram porém passou no nosso, por isso estes casos foram removidos.

In [29]:
stopwords_list = stopwords.words('portuguese')
print("aquele" in stopwords_list)

True

In [30]:
for i in gabarito['palavra'].to_list():
    if i.lower() in stopwords_list:
        print(i)

E
DO
DAS
DE
DA
DOS

In [31]:
gabarito_sem_stopword = gabarito[~gabarito['palavra'].str.lower().isin(stopwords_list)]

In [32]:
for i in gabarito_sem_stopword['palavra'].to_list():
    if i.lower() in stopwords_list:
        print(i)

In [33]:
gabarito_sem_stopword

            palavra  y
0           MARIETA  1
1               LUZ  1
2            ELIANE  1
3            GUSMÃO  1
4          MAURICIO  1
...             ... ..
11626        ICARAI  0
11627  PROCEDIMENTO  0
11628         AMARO  0
11629     PONTUACAO  0
11630  DESCONFORTOS  0

[11625 rows x 2 columns]

In [ ]:
gabarito_sem_stopword.to_csv(PATH_GABARITO, index = False)

In [34]:
# 1. Definimos o caminho absoluto exato para evitar erro de nível (../)
caminho_final = r'C:\Users\joaol\OneDrive\Desktop\MestradoBaseMédica\ProjetoDoutorado\BASES\experimento_corretor\gabarito_corretor_base_medica.csv'

In [35]:
# 2. Pegamos o diretório pai (C:\...\BASES\experimento_corretor)
diretorio = os.path.dirname(caminho_final)

In [36]:
# 4. Salvamos o seu DataFrame 'gabarito_sem_stopword'
gabarito_sem_stopword.to_csv(caminho_final, index=False)

print(f"🚀 Gabarito salvo com sucesso em: {caminho_final}")

🚀 Gabarito salvo com sucesso em: C:\Users\joaol\OneDrive\Desktop\MestradoBaseMédica\ProjetoDoutorado\BASES\experimento_corretor\gabarito_corretor_base_medica.csv