## Concatenaçao das bases BOS.xlsx e DECCC.xlsx

In [1]:
import pandas as pd
import os

In [2]:
from dotenv import load_dotenv
load_dotenv()

True

In [5]:
PATH_BASE_BOS = os.getenv('PATH_BASE_BOS')
PATH_BASE_DECCC = os.getenv('PATH_BASE_DECCC')
PATH_BASE_CONCATENADA_BOS_DECCC = os.getenv('PATH_BASE_CONCATENADA_BOS_DECCC')

In [4]:
df_origin = pd.read_excel(PATH_BASE_BOS, usecols=['n_bop', 'relato', 'NOMES']).dropna(subset=['NOMES']).reset_index()
df_new = pd.read_excel(PATH_BASE_DECCC, usecols=['n_bop', 'relato', 'nomes']).dropna(subset=['nomes']).reset_index()

In [3]:
linhas_sem_nomes = df_origin[df_origin['NOMES'].isna()]
linhas_sem_nomes

Empty DataFrame
Columns: [index, n_bop, relato, NOMES]
Index: []

In [4]:
linhas_sem_nomes = df_new[df_new['nomes'].isna()]
linhas_sem_nomes

Empty DataFrame
Columns: [index, n_bop, relato, nomes]
Index: []

In [ ]:
df = pd.DataFrame({'n_bop':pd.concat([df_origin['n_bop'], df_new['n_bop']], ignore_index=True),
                    'relato':pd.concat([df_origin['relato'], df_new['relato']], ignore_index=True),
                    'nomes': pd.concat([df_origin['NOMES'], df_new['nomes']], ignore_index=True)})

df = df.drop(columns=['nomes'])

In [ ]:
df.to_csv(PATH_BASE_CONCATENADA_BOS_DECCC, index=False)